spring.application.name=api
# -------------------------------------------------------------
# CONFIGURAÇÕES DO SERVIDOR
# -------------------------------------------------------------
# A porta onde a nossa API vai ficar há escuta
server.port=8080

# -------------------------------------------------------------
# LIGAÇÃO AO POSTGRESQL (Raspberry Pi)
# -------------------------------------------------------------
spring.datasource.url=jdbc:postgresql://192.168.1.64:5432/climbbeta_db
spring.datasource.username=climb_admin
spring.datasource.password=climb_password123
spring.datasource.driver-class-name=org.postgresql.Driver

# -------------------------------------------------------------
# LIGAÇÃO AO MINIO (Armazenamento de Objectos S3)
# -------------------------------------------------------------
minio.endpoint=http://192.168.1.64:9000
minio.access-key=minio_admin
minio.secret-key=minio_secret2026
minio.bucket-name=climbbeta-media
# Aumentar o limite de upload para 20MB
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB
